<?php

// Translation of file ./modules/siteclone/model.siteclone.inc

$_COS_LANG_MODULE['siteclone_legend'] = 'Opret website';
$_COS_LANG_MODULE['siteclone_label_sitename'] = 'Domæne navn (kun a-z og 0-9 - mindst 5 tegn)';
$_COS_LANG_MODULE['siteclone_label_email'] = 'Indtast en gyldig email';
$_COS_LANG_MODULE['siteclone_label_password'] = 'Password';
$_COS_LANG_MODULE['siteclone_label_password2'] = 'Gentag password';
$_COS_LANG_MODULE['siteclone_submit_text'] = 'Opret';
$_COS_LANG_MODULE['siteclone_confirm_legend'] = 'Bekræft oprettelse';
$_COS_LANG_MODULE['siteclone_error_sitename_length'] = 'Domæne navn skal være længere end 5 tegn';
$_COS_LANG_MODULE['siteclone_error_sitename_not_valid'] = 'Ikke et gyldigt domæne navn';
$_COS_LANG_MODULE['siteclone_error_sitename_exists'] = 'Domænet eksisterer';
$_COS_LANG_MODULE['siteclone_error_email_exists'] = 'Email eksisterer allerede';
$_COS_LANG_MODULE['siteclone_error_password_length'] = 'Password skal være mindst 7 tegn';
$_COS_LANG_MODULE['siteclone_error_password_no_match'] = 'Passwords matcher ikke';
$_COS_LANG_MODULE['siteclone_error_invalid_email'] = 'Ugyldig email';
$_COS_LANG_MODULE['siteclone_error_incorrect_captcha'] = 'Ikke et korrekt svar til captcha test';
$_COS_LANG_MODULE['siteclone_email_subject'] = 'Oprettelse af site';
// Translation of file ./modules/siteclone/rpc.php

$_COS_LANG_MODULE['siteclone_no_such_id'] = 'ID ikke fundet i database';
$_COS_LANG_MODULE['siteclone_already_validated'] = 'Domænet er allerede valideret';
// Translation of file ./modules/siteclone/index.php

$_COS_LANG_MODULE['siteclone_confirm_email'] = 'Der er afsendt en email. Check din mailbox og følg instruktioner';
$_COS_LANG_MODULE['siteclone_confirm_email_error'] = 'Der opstod en fejl og systemet kunne ikke afsende en email. Prøv at oprette et site senere';

$_COS_LANG_MODULE['siteclone_confirm_html_title'] = 'siteclone_confirm_html_title';
$_COS_LANG_MODULE['siteclone_rpc_created_config_dir'] = 'siteclone_rpc_created_config_dir';
$_COS_LANG_MODULE['siteclone_rpc_ini_file_exists'] = 'siteclone_rpc_ini_file_exists';
$_COS_LANG_MODULE['siteclone_rpc_could_not_make_ini_file'] = 'siteclone_rpc_could_not_make_ini_file';
$_COS_LANG_MODULE['siteclone_rpc_ini_file_created'] = 'siteclone_rpc_ini_file_created';
$_COS_LANG_MODULE['siteclone_rpc_could_not_make_database'] = 'siteclone_rpc_could_not_make_database';
$_COS_LANG_MODULE['siteclone_rpc_database_created'] = 'siteclone_rpc_database_created';
$_COS_LANG_MODULE['siteclone_rpc_could_not_make_base_tables'] = 'siteclone_rpc_could_not_make_base_tables';
$_COS_LANG_MODULE['siteclone_rpc_base_tables_created'] = 'siteclone_rpc_base_tables_created';
$_COS_LANG_MODULE['siteclone_rpc_could_not_install_modules'] = 'siteclone_rpc_could_not_install_modules';
$_COS_LANG_MODULE['siteclone_rpc_all_modules_installed'] = 'siteclone_rpc_all_modules_installed';
$_COS_LANG_MODULE['siteclone_rpc_could_not_set_template'] = 'siteclone_rpc_could_not_set_template';
$_COS_LANG_MODULE['siteclone_rpc_template_set'] = 'siteclone_rpc_template_set';
$_COS_LANG_MODULE['siteclone_rpc_could_not_make_user'] = 'siteclone_rpc_could_not_make_user';
$_COS_LANG_MODULE['siteclone_rpc_user_created'] = 'siteclone_rpc_user_created';
$_COS_LANG_MODULE['siteclone_rpc_confirm_message'] = 'siteclone_rpc_confirm_message';
$_COS_LANG_MODULE['siteclone_rpc_link_text'] = 'siteclone_rpc_link_text';
