<?php

// Translation of file ./modules/siteclone/model.siteclone.inc

$_COS_LANG_MODULE['siteclone_legend'] = 'Opret website';
$_COS_LANG_MODULE['siteclone_label_sitename'] = 'Domæne navn (kun a-z og 0-9 - mindst 5 tegn)';
$_COS_LANG_MODULE['siteclone_label_email'] = 'Indtast en gyldig email';
$_COS_LANG_MODULE['siteclone_label_password'] = 'Password';
$_COS_LANG_MODULE['siteclone_label_password2'] = 'Gentag password';
$_COS_LANG_MODULE['siteclone_submit_text'] = 'Opret';
$_COS_LANG_MODULE['siteclone_confirm_legend'] = 'Bekræft oprettelse';
$_COS_LANG_MODULE['siteclone_error_sitename_length'] = 'Domæne navn skal være længere end 5 tegn';
$_COS_LANG_MODULE['siteclone_error_sitename_not_valid'] = 'Ikke et gyldigt domæne navn';
$_COS_LANG_MODULE['siteclone_error_sitename_exists'] = 'Domænet eksisterer';
$_COS_LANG_MODULE['siteclone_error_email_exists'] = 'Email eksisterer allerede';
$_COS_LANG_MODULE['siteclone_error_password_length'] = 'Password skal være mindst 7 tegn';
$_COS_LANG_MODULE['siteclone_error_password_no_match'] = 'Passwords matcher ikke';
$_COS_LANG_MODULE['siteclone_error_invalid_email'] = 'Ugyldig email';
$_COS_LANG_MODULE['siteclone_error_incorrect_captcha'] = 'Ikke et korrekt svar til captcha test';
$_COS_LANG_MODULE['siteclone_email_subject'] = 'Oprettelse af site';
// Translation of file ./modules/siteclone/rpc.php

$_COS_LANG_MODULE['siteclone_no_such_id'] = 'ID ikke fundet i database';
$_COS_LANG_MODULE['siteclone_already_validated'] = 'Domænet er allerede valideret';
// Translation of file ./modules/siteclone/index.php

$_COS_LANG_MODULE['siteclone_confirm_email'] = 'Der er afsendt en email. Check din mailbox og følg instruktioner';
$_COS_LANG_MODULE['siteclone_confirm_email_error'] = 'Der opstod en fejl og systemet kunne ikke afsende en email. Prøv at oprette et site senere';
