<?php

$_COS_LANG_MODULE['ID does not exists in database. Request was canceled!'] = 'ID ikke findes i databasen. Anmodning blev aflyst!';
$_COS_LANG_MODULE['Domænet er allerede verificeret'] = 'Domænet ER already verificeret';
$_COS_LANG_MODULE['siteclone_rpc_created_config_dir'] = 'Skabte konfigurations dir
';
$_COS_LANG_MODULE['siteclone_rpc_ini_file_exists'] = 'Konfigurations fil eksisterer allerede.
';
$_COS_LANG_MODULE['siteclone_rpc_could_not_make_ini_file'] = 'Tell administer #¤%!&¤
Kan kke skabe ini fil
Sandsynligvis fordi web serveren ikke har de rette rettigheder. Prøv med:
./coscli.sh file --chmod-files
';
$_COS_LANG_MODULE['siteclone_rpc_ini_file_created'] = 'Konfigurations fil blev skabt
';
$_COS_LANG_MODULE['siteclone_rpc_could_not_make_database'] = 'Kunne ikke oprette database.
';
$_COS_LANG_MODULE['siteclone_rpc_database_created'] = 'Database blev oprettet
';
$_COS_LANG_MODULE['siteclone_rpc_could_not_make_base_tables'] = 'Kunne ikke oprettet basis tabeller i database.
';
$_COS_LANG_MODULE['siteclone_rpc_base_tables_created'] = 'Basis tabeller blev oprettet i database
';
$_COS_LANG_MODULE['siteclone_rpc_could_not_install_modules'] = 'Kunne ikke installere moduler!
';
$_COS_LANG_MODULE['siteclone_rpc_all_modules_installed'] = 'Alle moduler blev installeret
';
$_COS_LANG_MODULE['siteclone_rpc_could_not_set_template'] = 'Kunne ikke sætte standard template
';
$_COS_LANG_MODULE['siteclone_rpc_template_set'] = 'Standard template blev sat
';
$_COS_LANG_MODULE['siteclone_rpc_could_not_make_user'] = 'Kunne ikke skabe bruger
';
$_COS_LANG_MODULE['siteclone_rpc_user_created'] = 'Bruger blev oprettet
';
$_COS_LANG_MODULE['siteclone_site_created_final_message'] = 'Dit website er oprettet!';
$_COS_LANG_MODULE['siteclone_rpc_confirm_message'] = 'Dit site blev oprettet
';
$_COS_LANG_MODULE['siteclone_rpc_link_text'] = 'Login med email og password';
$_COS_LANG_MODULE['siteclone_initial_conditions_config_title'] = 'Indtast krav der skal accepteres, når klient opretter site';
$_COS_LANG_MODULE['siteclone_initial_conditions'] = 'siteclone_initial_conditions';
$_COS_LANG_MODULE['siteclone_rpc_please_wait_message'] = 'Vent veligst. Dette kan tage op til et minut eller to ...';
$_COS_LANG_MODULE['siteclone_confirm_html_title'] = 'Bekræft oprettelse af site';
$_COS_LANG_MODULE['siteclone_clone_site_html_title'] = 'Opret gratis website';
$_COS_LANG_MODULE['siteclone_site_meta_desc'] = 'Simple og brugervenligt CMS - ganske gratis!';
$_COS_LANG_MODULE['siteclone_confirm_email'] = 'Der er afsendt en email. Check din mailbox og følg instruktioner';
$_COS_LANG_MODULE['siteclone_confirm_email_error'] = 'Der opstod en fejl og systemet kunne ikke afsende en email. Prøv at oprette et site senere';
$_COS_LANG_MODULE['siteclone_legend'] = 'Opret website';
$_COS_LANG_MODULE['siteclone_label_accept_conditions'] = 'Jeg har læst og accepteret betingelserne';
$_COS_LANG_MODULE['siteclone_link_text_conditions'] = 'Læs betingelserne her';
$_COS_LANG_MODULE['siteclone_label_sitename'] = 'Domæne navn (kun a-z og 0-9 - mindst 5 tegn)';
$_COS_LANG_MODULE['siteclone_label_email'] = 'Indtast en gyldig email';
$_COS_LANG_MODULE['siteclone_label_password'] = 'Password';
$_COS_LANG_MODULE['siteclone_label_password2'] = 'Gentag password';
$_COS_LANG_MODULE['siteclone_submit_text'] = 'Opret';
$_COS_LANG_MODULE['siteclone_confirm_legend'] = 'Bekræft oprettelse';
$_COS_LANG_MODULE['siteclone_error_accept_conditions'] = 'Du skal acceptere betingelserne';
$_COS_LANG_MODULE['siteclone_error_sitename_length'] = 'Domæne navn skal mindst 5 tegn';
$_COS_LANG_MODULE['siteclone_error_sitename_not_valid'] = 'Ikke et gyldigt domæne navn';
$_COS_LANG_MODULE['siteclone_error_sitename_exists'] = 'Domænet eksisterer';
$_COS_LANG_MODULE['siteclone_error_email_exists'] = 'Email eksisterer allerede';
$_COS_LANG_MODULE['siteclone_error_password_length'] = 'Password skal være mindst 7 tegn';
$_COS_LANG_MODULE['siteclone_error_password_no_match'] = 'Passwords matcher ikke';
$_COS_LANG_MODULE['siteclone_error_invalid_email'] = 'Ugyldig email';
$_COS_LANG_MODULE['siteclone_error_incorrect_captcha'] = 'Ikke et korrekt svar til captcha test';
$_COS_LANG_MODULE['siteclone_email_subject'] = 'Oprettelse af site';
