<?php


// Translation of file /modules/siteclone/rpc.php

$_COS_LANG_MODULE['ID does not exists in database. Request was canceled!'] = 'ID does not exists in database. Request was canceled!';
$_COS_LANG_MODULE['Domænet er allerede verificeret'] = 'Domænet er allerede verificeret';
$_COS_LANG_MODULE['siteclone_rpc_created_config_dir'] = 'Created config dir
';
$_COS_LANG_MODULE['siteclone_rpc_ini_file_exists'] = 'Ini file already exists.
';
$_COS_LANG_MODULE['siteclone_rpc_could_not_make_ini_file'] = 'Administer has #¤%!&¤ up
Can not make ini file
Ask him to set correct permissions with this command:
./coscli.sh file --chmod-files
';
$_COS_LANG_MODULE['siteclone_rpc_ini_file_created'] = 'Config file has been created
';
$_COS_LANG_MODULE['siteclone_rpc_could_not_make_database'] = 'Could not create database. Something is wrong.
';
$_COS_LANG_MODULE['siteclone_rpc_database_created'] = 'Database has been created
';
$_COS_LANG_MODULE['siteclone_rpc_could_not_make_base_tables'] = 'Could not create base DB tables.
Something is not right.
';
$_COS_LANG_MODULE['siteclone_rpc_base_tables_created'] = 'Base Tables created
';
$_COS_LANG_MODULE['siteclone_rpc_could_not_install_modules'] = 'Could not install all modules. Site will not work!
';
$_COS_LANG_MODULE['siteclone_rpc_all_modules_installed'] = 'All modules was installed
';
$_COS_LANG_MODULE['siteclone_rpc_could_not_set_template'] = 'Could not set default template
';
$_COS_LANG_MODULE['siteclone_rpc_template_set'] = 'Default template has been set
';
$_COS_LANG_MODULE['siteclone_rpc_could_not_make_user'] = 'Could not create your user
';
$_COS_LANG_MODULE['siteclone_rpc_user_created'] = 'User has been created
';
$_COS_LANG_MODULE['siteclone_site_created_final_message'] = 'Your site has been created!';
$_COS_LANG_MODULE['siteclone_rpc_confirm_message'] = 'You site has been build. You can now go to';
$_COS_LANG_MODULE['siteclone_rpc_link_text'] = 'Login on your new site with email and password';

// Translation of file /modules/siteclone/configdb.inc

$_COS_LANG_MODULE['siteclone_initial_conditions_config_title'] = 'Enter site conditions - will be used in connection with a check box';
$_COS_LANG_MODULE['siteclone_initial_conditions'] = 'I have read and understood the conditions';

// Translation of file /modules/siteclone/confirm.php

$_COS_LANG_MODULE['siteclone_rpc_please_wait_message'] = 'Please Wait. This may take a minute or two ...';
$_COS_LANG_MODULE['siteclone_confirm_html_title'] = 'Confirm site creation';

// Translation of file /modules/siteclone/index.php

$_COS_LANG_MODULE['siteclone_clone_site_html_title'] = 'Opret gratis website';
$_COS_LANG_MODULE['siteclone_site_meta_desc'] = 'Simple and userfriendly CMS - For free!';
$_COS_LANG_MODULE['siteclone_confirm_email'] = 'An email has been sent, please check your mailbox in a few minutes for futher instructions';
$_COS_LANG_MODULE['siteclone_confirm_email_error'] = 'An error was encountered while trying to send an email. Please try to create a new site later';

// Translation of file /modules/siteclone/module.php

$_COS_LANG_MODULE['siteclone_legend'] = 'New Site Information';
$_COS_LANG_MODULE['siteclone_label_accept_conditions'] = 'Accept conditions';
$_COS_LANG_MODULE['siteclone_link_text_conditions'] = 'Read conditions';
$_COS_LANG_MODULE['siteclone_label_sitename'] = 'Sitename (a-z and 0-9 and at least 5 chars)';
$_COS_LANG_MODULE['siteclone_label_email'] = 'Email (have to be valid)';
$_COS_LANG_MODULE['siteclone_label_password'] = 'Enter Password';
$_COS_LANG_MODULE['siteclone_label_password2'] = 'Retype Password';
$_COS_LANG_MODULE['siteclone_submit_text'] = 'Submit';
$_COS_LANG_MODULE['siteclone_confirm_legend'] = 'Confirm Creation';
$_COS_LANG_MODULE['siteclone_error_accept_conditions'] = 'You will have to accept the conditions';
$_COS_LANG_MODULE['siteclone_error_sitename_length'] = 'Sitename needs to be at least 5 chars long';
$_COS_LANG_MODULE['siteclone_error_sitename_not_valid'] = 'Sitename not valid';
$_COS_LANG_MODULE['siteclone_error_sitename_exists'] = 'Sitename already exists';
$_COS_LANG_MODULE['siteclone_error_email_exists'] = 'Email already exists';
$_COS_LANG_MODULE['siteclone_error_password_length'] = 'Password needs to be at least 7 chars long';
$_COS_LANG_MODULE['siteclone_error_password_no_match'] = 'Passwords does not match';
$_COS_LANG_MODULE['siteclone_error_invalid_email'] = 'Not a valid email';
$_COS_LANG_MODULE['siteclone_error_incorrect_captcha'] = 'Please enter correct captcha';
$_COS_LANG_MODULE['siteclone_email_subject'] = 'Creation of site';
