<?php

// Translation of file ./modules/siteclone/model.siteclone.inc

$_COS_LANG_MODULE['siteclone_legend'] = 'New Site Information';
$_COS_LANG_MODULE['siteclone_label_sitename'] = 'Sitename (a-z and 0-9 and at least 5 chars)';
$_COS_LANG_MODULE['siteclone_label_email'] = 'Email (have to be valid)';
$_COS_LANG_MODULE['siteclone_label_password'] = 'Enter Password';
$_COS_LANG_MODULE['siteclone_label_password2'] = 'Retype Password';
$_COS_LANG_MODULE['siteclone_submit_text'] = 'Submit';
$_COS_LANG_MODULE['siteclone_confirm_legend'] = 'Confirm Creation';
$_COS_LANG_MODULE['siteclone_error_sitename_length'] = 'Sitename needs to be at least 5 chars long';
$_COS_LANG_MODULE['siteclone_error_sitename_not_valid'] = 'Sitename not valid';
$_COS_LANG_MODULE['siteclone_error_sitename_exists'] = 'Sitename already exists';
$_COS_LANG_MODULE['siteclone_error_email_exists'] = 'Email already exists';
$_COS_LANG_MODULE['siteclone_error_password_length'] = 'Password needs to be at least 7 chars long';
$_COS_LANG_MODULE['siteclone_error_password_no_match'] = 'Passwords does not match';
$_COS_LANG_MODULE['siteclone_error_invalid_email'] = 'Not a valid email';
$_COS_LANG_MODULE['siteclone_error_incorrect_captcha'] = 'Please enter correct captcha';

$_COS_LANG_MODULE['siteclone_email_subject'] = 'Creation of site';
$_COS_LANG_MODULE['siteclone_no_such_id'] = 'siteclone_no_such_id';
$_COS_LANG_MODULE['siteclone_already_validated'] = 'siteclone_already_validated';

$_COS_LANG_MODULE['siteclone_confirm_email'] = 'An email has been sent, please check your mailbox in a few minutes for futher instructions';
$_COS_LANG_MODULE['siteclone_confirm_email_error'] = 'An error was encountered while trying to send an email. Please try to create a new site later';
