Hej (næsten) ny ejer af siden <?=$vars['sitename']?>!

For at fuldføre oprettelsen af dit nye site skal du trykke på det følgende link. Hvis du ikke kan trykke direkte på det skal du kopiere det og indsætte det i URL linien af din browser:

<?=$vars['confirm_link'] ?>

Linket vil tage dig selve oprettelses processen. 

Dette kan tage op til et minut, så hav en vis form for tålmodighed!

Vh <?=$vars['sender_site']?>
